# 3. Interactive Computation

## 3.1 Matrices and Vectors

### 3.1.1 Input

In [2]:
import numpy as np

A = np.array([[1, 2, 5], [3, 9, 0]], dtype=float)
print A
x = 1
y = 2
B = np.array([[2*x, np.log(x)+np.sin(y)], [5j, 3+2j]])
print B

[[ 1.  2.  5.]
 [ 3.  9.  0.]]
[[ 2.00000000+0.j  0.90929743+0.j]
 [ 0.00000000+5.j  3.00000000+2.j]]


### 3.1.2 Indexing (or subscripting)

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 8]], dtype=float)
print A

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  8.]]


In [4]:
print A[1,2]

6.0


In [6]:
A[2,2] = 9
print A

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


In [18]:
B = A[1:, :]
print B

[[ 4.  5.  6.]
 [ 7.  8.  9.]]


In [21]:
C = np.delete(B, np.s_[1], 1)
print C

[[ 4.  6.]
 [ 7.  9.]]


In [25]:
Q = np.array([[2, 3, 6, 0, 5], [0, 0, 20, -4, 3], [1, 2, 3, 9, 8], [2, -5, -5, -5, 6], [5, 10, 15, 20, 25]])
v = np.array([0, 3, 4])
print Q[v, :]
print Q[:,v]

[[ 2  3  6  0  5]
 [ 2 -5 -5 -5  6]
 [ 5 10 15 20 25]]
[[ 2  0  5]
 [ 0 -4  3]
 [ 1  9  8]
 [ 2 -5  6]
 [ 5 20 25]]


In [34]:
a = np.arange(1, 37)
print a
b = a.reshape((9,4))
print a
print b

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]]


In [35]:
c = a.reshape((3,12))
print c

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32 33 34 35 36]]


In [33]:
d = np.reshape(a, (4,9))
print a
print d

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36]
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]]


#### Transpose

In [36]:
A = np.array([[2, 3], [6, 7]])
B = A.T
print A
print B

[[2 3]
 [6 7]]
[[2 6]
 [3 7]]


In [38]:
C = np.array([[2, 3+1j], [6j, 7j]])
Ct = C.T
print Ct
print

[[ 2.+0.j  0.+6.j]
 [ 3.+1.j  0.+7.j]]



#### Appending a row or a column

In [48]:
A = np.eye(3,3)
print A
u = np.array([5, 6, 7])
print u
v = np.array([2, 3, 4])
print v

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[5 6 7]
[2 3 4]


In [46]:
B = np.insert(A, 3, u, axis=0)
print B

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 5.  6.  7.]]


In [49]:
C = np.insert(A, 3, v, axis=1)
print C

[[ 1.  0.  0.  2.]
 [ 0.  1.  0.  3.]
 [ 0.  0.  1.  4.]]


#### Utility matrices

In [50]:
a = np.eye(3, 3)
print a

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [52]:
b = np.zeros((5, 5))
print b

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [53]:
b[:3, :3] = np.ones((3, 3))
print b

[[ 1.  1.  1.  0.  0.]
 [ 1.  1.  1.  0.  0.]
 [ 1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [55]:
b[3:, 3:] = np.eye(2, 2) * 4
print b

[[ 1.  1.  1.  0.  0.]
 [ 1.  1.  1.  0.  0.]
 [ 1.  1.  1.  0.  0.]
 [ 0.  0.  0.  4.  0.]
 [ 0.  0.  0.  0.  4.]]


In [56]:
print np.diag(b)

[ 1.  1.  1.  4.  4.]


In [57]:
print np.diag(b, 1)

[ 1.  1.  0.  0.]


In [62]:
d = np.arange(2, 9, 2)
d1 = np.array([-3, -3, -3])
d2 = np.array([-1, -1])
print d
print d1
print d2

D = np.diag(d) + np.diag(d1, 1) + np.diag(d2, -2)
print D

[2 4 6 8]
[-3 -3 -3]
[-1 -1]
[[ 2 -3  0  0]
 [ 0  4 -3  0]
 [-1  0  6 -3]
 [ 0 -1  0  8]]


### 3.1.4 Creating vectors

In [63]:
a = np.array(range(0, 101, 10))
print a

[  0  10  20  30  40  50  60  70  80  90 100]


In [66]:
b = np.arange(0, 2*np.pi + np.pi/100, np.pi/50)
print b

[ 0.          0.06283185  0.12566371  0.18849556  0.25132741  0.31415927
  0.37699112  0.43982297  0.50265482  0.56548668  0.62831853  0.69115038
  0.75398224  0.81681409  0.87964594  0.9424778   1.00530965  1.0681415
  1.13097336  1.19380521  1.25663706  1.31946891  1.38230077  1.44513262
  1.50796447  1.57079633  1.63362818  1.69646003  1.75929189  1.82212374
  1.88495559  1.94778745  2.0106193   2.07345115  2.136283    2.19911486
  2.26194671  2.32477856  2.38761042  2.45044227  2.51327412  2.57610598
  2.63893783  2.70176968  2.76460154  2.82743339  2.89026524  2.95309709
  3.01592895  3.0787608   3.14159265  3.20442451  3.26725636  3.33008821
  3.39292007  3.45575192  3.51858377  3.58141563  3.64424748  3.70707933
  3.76991118  3.83274304  3.89557489  3.95840674  4.0212386   4.08407045
  4.1469023   4.20973416  4.27256601  4.33539786  4.39822972  4.46106157
  4.52389342  4.58672527  4.64955713  4.71238898  4.77522083  4.83805269
  4.90088454  4.96371639  5.02654825  5.0893801   5.

In [67]:
x = np.linspace(0, 20, 5)
print x

[  0.   5.  10.  15.  20.]


In [68]:
v = np.logspace(0, 3, 4)
print v

[    1.    10.   100.  1000.]


In [71]:
u = np.zeros(10)
print u

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [70]:
v = np.zeros((10,1))
print v

[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]


### 3.2 Matrix and Array Operations

### 3.2.1 Arithmetic operations

In [72]:
A = np.arange(1, 10).reshape((3, 3))
print A

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [74]:
x = A[0, :].reshape(3,1)
print x

[[1]
 [2]
 [3]]


In [75]:
a = np.dot(x.T, x)
print a

[[14]]


In [76]:
b = np.dot(x, x.T)
print b

[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [77]:
c = np.dot(A, x)
print c

[[14]
 [32]
 [50]]


In [79]:
print np.dot(A, A)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [80]:
print A*A

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [81]:
print A**2

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


### 3.2.2 Relational operations

In [82]:
x = np.array([1, 5, 3, 7])
y = np.array([0, 2, 8, 7])
print x < y

[False False  True False]


In [83]:
print x <= y

[False False  True  True]


In [84]:
print x > y

[ True  True False False]


In [85]:
print x >= y

[ True  True False  True]


In [86]:
print x == y

[False False False  True]


In [103]:
print x != y

[False  True  True False]


### 3.2.3 Logical operations

In [97]:
x = np.array([0, 5, 3, 7])
y = np.array([0, 2, 8, 7])
m = (x > y) & (x > 4)
print m

[False  True False False]


In [93]:
n = (x > 0) | (y > 0)
print n

[False  True  True  True]


In [101]:
m = ~((x > 0) | (y > 0))
print m

[ True False False False]


### 3.2.4 Elementary math functions

In [104]:
q = np.array([0, np.pi/2, np.pi])
x = np.array([1, -1, -1, 1])
y = np.array([1, 1, -1, -1])
print np.sin(q)

[  0.00000000e+00   1.00000000e+00   1.22464680e-16]


In [105]:
print np.sinh(q)

[  0.           2.3012989   11.54873936]


In [107]:
print np.arctan(y / x)

[ 0.78539816 -0.78539816  0.78539816 -0.78539816]


In [109]:
print np.arctan2(y, x)

[ 0.78539816  2.35619449 -2.35619449 -0.78539816]
