# Introduction to Python

* Python is a general purpose programming language with strong support for numerical computations
* Original Python implementation is CPython, which is written in C. Hence you can easily include C/C++ code into Python
* Huge collection of useful modules and packages for general as well as numerical computation applications
* Mature programming language with support for imperative programming and limited support for functional programming
* Under imperative programming paradigm, supports both **object oriented** and **procedural programming**
* Python is a dynamic (interpreted) programming language
* Python is case sensitive and weakly typed (data type of objects need not be declared before being used, and can be changed during program execution)
* Indentation is required, not optional
* There are two versions of Python available at this point of time, Python 2.7.x and Python 3.3.x. Python 3 is not fully backward compatible with  Python 2
* We are using Python 2.7.x

## Some Points to Remember
* Python is case sensitive, similar to C
* Python requires strict indentation to indicate blocks of code, **indentation is compulsory, not optional**
* Python is a dynamic programming language - data type of an object can be changed at different points of your program
* Base installation of Python does not have an array implementation, instead it offers a List implementation
* Base installation of Python does not have built-in math functions such as **`sqrt()`**, you must import the **`math`** module to use such functions
* Single line comments begin with **`#`** and end at the end of line

## Versions of Python
Currently there are two versions of Python that are available for use and are under development. **Python 2** is currently in version **2.7.x** and **Python 3** is in version **3.4.x**. In the near future, development will stop for Python 2.

There are some differences from Python 2 to Python 3 that are not backward compatible. Some of them which affect scientific computing are:
* **`print`** is a statement in Python 2 where as it is a function in Python 3.
* In Python 2, **`/`** performs an integer division when both numerator and denominator are integers and a floating point division if one or both of them are floating point numbers. In Python 3, **`/`** always performs a floating point division (even when both numerator and denominatoe are integers) and a new operator **`//`** is available to perform integer division

This behaviour of Python 3 can be used in Python 2 with the help of **`from __future__ import print_function, division`** import statement. We will use this throughout this workshop.

In [6]:
print(2/3)
print(3/2)
print(3//2)

from __future__ import division, print_function

print(2/3)
print(3/2)
print(3//2)

0.666666666667
1.5
1
0.666666666667
1.5
1


In [1]:
import sys

print(sys.version)

2.7.9 |Continuum Analytics, Inc.| (default, Dec 15 2014, 10:33:51) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]


## Creating Variables and Determining Their Type

Data type of an object is determined automatically by Python. Python understands complex numbers.

### Basic Data Types
* `int` - Integer
* `float` - Floating point number
* `complex` - Complex number
* `bool` - Boolean

In [3]:
from __future__ import print_function, division

a = 10
print('a =', a, type(a))
b = 2.5
print('b =', b, type(b))
c = 1e3
print('c =', c, type(c))
d = 1 + 2j
print('d =', d, type(d))
f = 2 < 3
print(f, type(f))

a = 10 <type 'int'>
b = 2.5 <type 'float'>
c = 1000.0 <type 'float'>
d = (1+2j) <type 'complex'>
True <type 'bool'>


### Container Types
* `str` - String
* `list` - List
* `tuple` - Tuple
* `dict` - Dictionary
* `set` - Set

### Strings

In [4]:
a = 'Python'
print(a, type(a))
b = "Hubballi, Karnataka"
print(b, type(b))
print(a[0])
print(a[1])
print('Length =', len(a))

Python <type 'str'>
Hubballi, Karnataka <type 'str'>
P
y
Length = 6


### Indexing and Slicing Container Data Types (Strings, Lists, Tuples)
* Indexing starts with 0 (**zero**)
* Indices are positive in the forward direction and negative in the reverse direction
* Index $0$ is the initial ement
* Index $-1$ is the last element

In [5]:
print(a[0])
print(a[1])
print(a[-1])
print(a[-2])

P
y
n
o


In [5]:
for i, ch in enumerate(a):
    print(i, ch)

0 g
1 n
2 u
3 N
4 i
5 f
6 y
7  
8 2
9 0
10 1
11 5


### Lists
* List is a container for heterogeneous data element
* List elements can be accessed through indexing
* Lists are mutable - the value of the elements of a list can be changed

In [6]:
x = [10, 20, 'Pune', 2+0j, ]
print('Length =', len(x), 'Type =', type(x))
print(x[0], x[1], x[2], x[3])
print(x[-1], x[-2], x[-3], x[-4])
print(x[0:2])
print(x[-1:-3:-1])

x[1] = 200
print(x)

Length = 4 Type = <type 'list'>
10 20 Pune (2+0j)
(2+0j) Pune 20 10
[10, 20]
[(2+0j), 'Pune']
[10, 200, 'Pune', (2+0j)]


### Tuples
* Tuples are similar to Lists, but are **immutable** -the value of their elements cannot be changed 

In [9]:
x = (10, 20, 'Pune', 2+0j)
print('Length =', len(x), 'Type =', type(x))
print(x[0], x[1], x[2], x[3])
print(x[-1], x[-2], x[-3], x[-4])
print(x[0:2])
print(x[-1:-3:-1])

x[1] = 200  # ERROR

Length = 4 Type = <type 'tuple'>
10 20 Pune (2+0j)
(2+0j) Pune 20 10
(10, 20)
((2+0j), 'Pune')


TypeError: 'tuple' object does not support item assignment

### Tuple with One Element

In [8]:
a = (10)
print(type(a))
b = (10,)
print(type(b))

<type 'int'>
<type 'tuple'>


### Dictionaries
* Dictionaries are (key, value) pairs
* Indexing is done using the keys

In [ ]:
d = {'a': 10, 'b': 20, 'name': "Satish", 'email': 'satish.annigeri@gmail.com'}
print('Length =', len(d), type(d))
print(d.keys())

## Operations, Expressions and Statements
### Numbers
* Addition +, Subtraction -, Multiplication `*`, Division `/`
* Modulo division **`%`**
* Exponentiation `**`

In [ ]:
a = 10; b = 20; c = a + b
print(type(c), c)
a = 10.0; b = 20; c = a + b
print(type(c), c)

In [ ]:
a = 7; b = 3; c = a / b
print(c)
d = a // b
print(d)

In [ ]:
d = a % b
print(d)
print(7.0 % 3.0)

In [ ]:
print(2**2)
print(2**0.5)
print(2**-1)

### Standard Functions

In [3]:
print(abs(-10))
print(abs(-10.5))
print(abs(3+4j))
print(sum([10, 20, 30]))
print(sum((10, 30, 50)))
print(min([-10, 0, 5]))
print(max([-10, 0, 5]))

10
10.5
5.0
60
90
-10
5


### Mathematical Functions

Mathematical functions similar to the C math library functions available in **`math.h`** are available in a module **`math`**. A module, such as **``math``** may contain data (such as **``math.pi``**) and functions (such as **``math.sqrt``**). Importing a module creates a new namespace, containing everything the module contains. To use these data and/or functions, use the name of the module.

In [ ]:
import math
help(math.sqrt)

In [ ]:
print(math.sqrt(10))
print(math.sqrt(-10))

In [ ]:
print(math.pi)
print(math.sin(math.pi/4))
print(math.acos(-1))
print(math.exp(1))
print(math.log(10))
print(math.log10(10))

In [ ]:
import cmath

print(cmath.sqrt(-2))
print(cmath.sin(2j))

## Copying Lists


### List assignemt creates an alias not a copy

In [ ]:
a = [1, 2, 3, 4, 5]
b = a         # This is an alias, not a copy
print 'a =', a
print 'b =', b
a[0] = 100
print 'a =', a
print 'b =', b

It is possible to make a copy of a list

In [ ]:
a = [1, 2, 3, 4, 5]
print a
c = a[:]       # c is a copy, not an alias
a[0] = 100
print 'a =', a
print 'c =', c

# Boolean operations on a list

In [5]:
a = [1, 2, 3, 4, 5]
b = a
c = a[:]
print(a == b)
print(a == c)
c[0] = 10
print(a == c)
print(1 in a)
print(100 in a)

True
True
False
True
False


# Append, Extend, Insert, Delete, Pop
## Append an item to a list

In [ ]:
a = [1, 2, 3, 4, 5]
print(a)
a.append(6)
print(a)
a.pop()
print(a)
x = a.pop(1)  # Pop item at index 1 and return it in x
print(a, x)

## Extend a list

In [6]:
a = [1, 2, 3]
b = [4, 5, 6]
c = a + b       # Return a new list which is an extension of a
print(a, b, c)
a.extend(b)     # Extend in place
print(a)
a = a + b
print(a)

[1, 2, 3] [4, 5, 6] [1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 4, 5, 6]


## Insert items into a list

In [7]:
a = [1, 2, 3, 4, 5]
print(a)
a.insert(0, 10)
print(a)
del(a[0])
print(a)

[1, 2, 3, 4, 5]
[10, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


In [8]:
print(a)
a.reverse()
print(a)
a.sort()
print(a)

[1, 2, 3, 4, 5]
[5, 4, 3, 2, 1]
[1, 2, 3, 4, 5]


In [9]:
a = [1, 2, 10, 4, 5, 10]
print(a.index(1))   # Index of item in list having the given value
print(a.index(10))

0
2


## List repetition adds one level deep

In [10]:
a = [1, 2, 3, 4]
b = a * 2
print(a)
print(b)
c = [a] * 2
print(c)

[1, 2, 3, 4]
[1, 2, 3, 4, 1, 2, 3, 4]
[[1, 2, 3, 4], [1, 2, 3, 4]]


# Lists can contain heterogenous items

In [12]:
a = [1, 'spam', [10, 20, 30]]  # Items in a list can be of different types
print(a)
print(a[0], type(a[0]))
print(a[1], type(a[1]))
print(a[2], type(a[2]))
print(a[2][0], a[2][1], a[2][2])

[1, 'spam', [10, 20, 30]]
1 <type 'int'>
spam <type 'str'>
[10, 20, 30] <type 'list'>
10 20 30


# List Comprehension


In [13]:
a = [1, 2, 3, 4, 5]
b = [r*2 for r in a]
print(type(a), a, type(b), b)

<type 'list'> [1, 2, 3, 4, 5] <type 'list'> [2, 4, 6, 8, 10]


In [14]:
c = [x**2 for x in a]
print(type(c))
print(c)

<type 'list'>
[1, 4, 9, 16, 25]


## Unpacking Lists and Tuples

Individual items of a List or Tuple can be unpacked and copied into individual objects.

In [12]:
x = [10, 20, 30]
a, b, c = x
print(a, b, c)

x, y, z = (100, 200, 300)
print(x, y, z)

a, b = [1, 2, 3]
print(a, b)

10 20 30
100 200 300


ValueError: too many values to unpack

## Output to Standard Output

1. **`print()`** function prints to standard output, after converting to string if necessary
2. By default, **`print()`** prints a newline character at the end of each call
3. Format strings similar to those used by **`printf()`** in C can be used to format the output

In [3]:
print("Hell world!")

Hell world!


In [10]:
print(2/3)
print("%.3f" % (2/3))
print("The sum of %d and %d is %d" % (2, 3, 2+3))

0.666666666667
0.667
The sum of 2 and 3 is 5


In [15]:
print(2, end=", ")
print(3)

2, 3


In [20]:
name = 'Vijay'
print('Hello, %s' % name)
print("Hello, {0}".format(name))
print("Hello, {0}, today is a {1}".format(name, 'Saturday'))
print("How are you this {1} {0}?".format(name, 'Saturday'))

Hello, Vijay
Hello, Vijay
Hello, Vijay, today is a Saturday
How are you this Saturday Vijay?


## Input from Standard Input

* Input from keyboard in console applications is one of the weaknesses of Python.
* Python has file operation functiions to read from or write to text or binary files, along similar lines to C programming language.
* Python can read from and write to CSV and Microsoft files

In [16]:
x = int(raw_input("Enter an integer: "))
print(x, type(x))
y = input("Enter a floating point number: ")
print(y, type(y))

Enter an integer: 100
100 <type 'int'>
Enter a floating point number: 2.5
2.5 <type 'float'>


## Functions to Create Lists
You can use the following functions to create lists with equally spaced points:

* **`range()`** generates a list of integers
* **`numpy.arange()`** generates an array of floating point numbers
* **`numpy.linspace()`** generates an array of equally spaced data points

## `range()`
Lists with regularly spaced integer elements can be generated using the **`range()`** function.

**`range()`** can be used in one of three ways:
1. **One argument:** Argument is the end value, start value is **0** and increment is **1**.
2. **Two arguments:** First argument is the start value, second argument is the end value and increment is assumed to be **1**.
3. **Three arguments:** First argument is the start value, second argument is the end value and the third argument is the increment/decrement.

**Note:** Ending value itself is not included in the List.

In [28]:
print(range(5))
print(range(-5))
print(range(1, 5))
print(range(5, 1))
print(range(5, 0, -1))
print(range(0, 10, 2))
print(10, 0, -2)

[0, 1, 2, 3, 4]
[]
[1, 2, 3, 4]
[]
[5, 4, 3, 2, 1]
[0, 2, 4, 6, 8]
10 0 -2


In [30]:
x = range(10)
print(type(x), len(x), x)

<type 'list'> 10 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


## `numpy.arange()`

**`np.arange()`** is similar to **`range()`**, but returns a **numpy array**, and values can be real numbers, and not restricted to integers.

NumPy module has a function **arange()** that is similar to **range()** except that:
* **`arange()`** creates an array not a List
* **`arange()`** can take real number increments and decrements

In [33]:
import numpy as np

x = np.arange(5)
print(type(x), len(x), x)

x = np.arange(0, 5, 0.5)
print(x)

x = np.arange(5, 0, -0.5)
print(x)

<type 'numpy.ndarray'> 5 [0 1 2 3 4]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5]
[ 5.   4.5  4.   3.5  3.   2.5  2.   1.5  1.   0.5]


## `numpy.linspace()`
**`np.linspace()`** generates a sequence of a specified number of equidistance points between given starting and ending values, both values inclusive. It takes three arguments, first and second are the starting and ending values respectively. Third is the number of points to be generated.

Unlike **`range()`** and **`numpy.arange()`**, the sequence **includes** the ending value. Instead of an increment/decrement, it takes the number of equally spaced points to be generated from the given start point to the given end point, both included. 

In [72]:
a = np.linspace(0, 5, 11)
print(type(a), len(a), a)

b = np.linspace(5.0, 0.0, 11)
print(b)

<type 'numpy.ndarray'> 11 [ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5. ]
[ 5.   4.5  4.   3.5  3.   2.5  2.   1.5  1.   0.5  0. ]


In [73]:
a = np.linspace(0, 5, 6)
print(type(a), a)
b = np.linspace(0, 5, 11)
print(b)

<type 'numpy.ndarray'> [ 0.  1.  2.  3.  4.  5.]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5. ]


## Importing Modules and Packages

* A **module** is a collection of functions, and optionally classes and data, similar to what other programming languages call **libraries**
* A **package** is a collection of modules
* To use a module or a package, you must first import it
* Usually importing a module creates a **new namespace** containing everything the module contains
* To use a member of a namespace, you must prepend the name of the object with its namespace

There are several different ways to import a module, each with its associated merits and demerits. The simplest way is to import a module and create a new name space and use the namespace to refer to its members

In [35]:
import numpy

a = numpy.array([1, 2, 3, 4, 5])
print(type(a), a)

<type 'numpy.ndarray'> [1 2 3 4 5]


You can assign an alternative name to the module when you import it, to simplify the typing.

In [37]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(type(a), a)

<type 'numpy.ndarray'> [1 2 3 4 5]


You can import selected objects from a module and merge it with the default namespace. But it is considered better practice to retain the namespace and not merge it with the default namespace.

In [39]:
from numpy import array

a = array([1, 2, 3, 4, 5])
print(type(a), a)

<type 'numpy.ndarray'> [1 2 3 4 5]


It is possible to import multiple objects from a module and merge them with the default namespace

In [42]:
from numpy import zeros, ones

a = zeros((3, 4), dtype=float)
print(a)
b = ones((4, 5), dtype=float)
print(b)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


It is possible to import every object from a module and merge them with the default namespace, **but you are strongly encouraged never to use it**.

In [44]:
from numpy import *

a = diag([1, 2, 3, 4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


You can assign alternate name to an object when you import it from a module and merge it with the default namespace.

In [47]:
from math import sqrt as mysqrt
from cmath import sqrt as csqrt

print(mysqrt(10))
print(csqrt(-10))

3.16227766017
3.16227766017j


## `math` Module

The **`math`** module contains all functions and constants available in the **C** **`math`** library, that is, functions listed in the **`math.h`** C header file.

In [53]:
import math

help(math)

Help on built-in module math:

NAME
    math

FILE
    (built-in)

DESCRIPTION
    This module is always available.  It provides access to the
    mathematical functions defined by the C standard.

FUNCTIONS
    acos(...)
        acos(x)
        
        Return the arc cosine (measured in radians) of x.
    
    acosh(...)
        acosh(x)
        
        Return the hyperbolic arc cosine (measured in radians) of x.
    
    asin(...)
        asin(x)
        
        Return the arc sine (measured in radians) of x.
    
    asinh(...)
        asinh(x)
        
        Return the hyperbolic arc sine (measured in radians) of x.
    
    atan(...)
        atan(x)
        
        Return the arc tangent (measured in radians) of x.
    
    atan2(...)
        atan2(y, x)
        
        Return the arc tangent (measured in radians) of y/x.
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(...)
        atanh(x)
        
        Return the hyperbolic arc tangen

In [61]:
print(math.pi)
print(math.fabs(-2.5))
print(abs(-2.5))
print(math.sin(math.pi/4))
print(math.atan(1.0)*4)

3.14159265359
2.5
2.5
0.707106781187
3.14159265359


The **`math`** module only operates on real numbers but cannot operate on imaginary numbers. For operations on complex numbers, use the **`cmath`** module.

In [63]:
print(math.sqrt(-4))

ValueError: math domain error

In [71]:
import cmath

print(cmath.sqrt(-4))
print(abs(2+3j))
print(math.sqrt(2**2 + 3**2))

2j
3.60555127546
3.60555127546
