#Numpy
## Introduction to some important routines

In [45]:
from __future__ import division, print_function
import numpy as np
x = np.array([1, 2, 3], dtype = float)
y = np.array([4, 5, 6], dtype = float)
print (x + y)

[ 5.  7.  9.]


In [46]:
print (x - y); print (x * y); print (x/y); print (x**y)

[-3. -3. -3.]
[  4.  10.  18.]
[ 0.25  0.4   0.5 ]
[   1.   32.  729.]


In [47]:
a = np.array([[1, 2], [3, 4]], dtype = float)
b = np.array([[5, 6], [7, 8]], dtype = float)
c = a*b
print (a,'\n', b,'\n', c,'\n')

[[ 1.  2.]
 [ 3.  4.]] 
 [[ 5.  6.]
 [ 7.  8.]] 
 [[  5.  12.]
 [ 21.  32.]] 



In [48]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype = float)
b = np.array([10, 20], dtype = float)
print (a+b)

[[ 11.  22.]
 [ 13.  24.]
 [ 15.  26.]]


* Here, the one-dimensional array `b` was broadcasted to a two-dimensional array that matched the size of `a`.
* In essence, `b` was repeated for each item in `a`, as if it were given by
**array ([[10, 20], [10, 20], [10, 20]])**

In [49]:
a = np.array([[1, 2], [3, 4]], dtype = float)
b = np.array([[5, 6], [7, 8]], dtype = float)
print (np.sqrt(a),'\n', np.sqrt(b))

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]] 
 [[ 2.23606798  2.44948974]
 [ 2.64575131  2.82842712]]


In [50]:
c = np.array([1.2, 3.6, 5.8 ], dtype = float)
print (np.floor(c),'\n', np.ceil(c),'\n', np.rint(c))

[ 1.  3.  5.] 
 [ 2.  4.  6.] 
 [ 1.  4.  6.]


In [51]:
a = np.array([1.5, 2.6, 3.4], dtype = float)
print (a.sum(),'\n', np.sum(a),'\n', a.prod(),'\n', np.prod(a))

7.5 
 7.5 
 13.26 
 13.26


In [52]:
a = np.random.rand(10)
print (np.mean(a),'\n', np.var(a),'\n', np.std(a),'\n', a.min(),'\n', a.max(),'\n', a.argmin(),'\n', a.argmax())

0.419613597797 
 0.101810507895 
 0.319077589146 
 0.0112322232899 
 0.915993677002 
 3 
 2


In [53]:
print (np.sort(a))

[ 0.01123222  0.02982997  0.1619095   0.17568617  0.21388942  0.53165402
  0.67806328  0.7116964   0.76618132  0.91599368]


In [54]:
a = np.array([2.5, np.NaN, np.Inf], dtype = float)
print (np.isnan(a),'\n', np.isfinite(a))

[False  True False] 
 [ True False False]


##Vector and Matrix operations

In [55]:
a = np.array([1, 2, 3], dtype = float); b = np.array([4, 5, 6], dtype = float)
print (np.dot(a, b))

32.0


In [56]:
a = np.array([[1, 2], [4, 5]], dtype = float)
b = np.array([7, 8], dtype = float)
print (a,'\n', b,'\n', np.dot(a, b),'\n', np.dot(b, a))

[[ 1.  2.]
 [ 4.  5.]] 
 [ 7.  8.] 
 [ 23.  68.] 
 [ 39.  54.]


In [57]:
a = np.array([1, 4, 0], dtype = float)
b = np.array([2, 2, 1], dtype = float)
np.outer(a, b)

array([[ 2.,  2.,  1.],
       [ 8.,  8.,  4.],
       [ 0.,  0.,  0.]])

In [58]:
np.inner(a, b)

10.0

In [59]:
np.cross(a, b)

array([ 4., -1., -6.])

In [61]:
a = np.array([[4, 2, 0], [9, 3, 7], [1, 2, 1]], dtype = float)
np.linalg.det(a)

-48.000000000000028

In [62]:
vals, vecs = np.linalg.eig(a)
print (vals, '\n', vecs)

[ 8.85591316  1.9391628  -2.79507597] 
 [[-0.3663565  -0.54736745  0.25928158]
 [-0.88949768  0.5640176  -0.88091903]
 [-0.27308752  0.61828231  0.39592263]]


In [63]:
b = np.linalg.inv(a)
print(b, '\n', np.dot(a, b))

[[ 0.22916667  0.04166667 -0.29166667]
 [ 0.04166667 -0.08333333  0.58333333]
 [-0.3125      0.125       0.125     ]] 
 [[  1.00000000e+00   5.55111512e-17   0.00000000e+00]
 [  0.00000000e+00   1.00000000e+00   2.22044605e-16]
 [  0.00000000e+00   1.38777878e-17   1.00000000e+00]]


In [68]:
a = np.array([[1, 3, 4], [5, 2, 3]], dtype = float)
U, s, V = np.linalg.svd(a)
print (U, '\n', s, '\n', V, '\n', np.dot(U, U.T))

[[-0.6113829  -0.79133492]
 [-0.79133492  0.6113829 ]] 
 [ 7.46791327  2.86884495] 
 [[-0.61169129 -0.45753324 -0.64536587]
 [ 0.78971838 -0.40129005 -0.46401635]
 [-0.046676   -0.79349205  0.60678804]] 
 [[  1.00000000e+00   1.11022302e-16]
 [  1.11022302e-16   1.00000000e+00]]


## Polynomials

In [73]:
np.poly([3, 10]) # Gives polynomial coefficients taking roots as input

array([  1, -13,  30])

In [74]:
np.roots([1, -13, 30]) # Gives polynomial roots taking coefficients as input

array([ 10.,   3.])

In [75]:
np.polyint([1, 1, 1, 1]) # Integrates the coefficients of polynomial

array([ 0.25      ,  0.33333333,  0.5       ,  1.        ,  0.        ])

In [77]:
np.polyder([0.25, 0.33333, 0.5, 1, 0])

array([ 1.     ,  0.99999,  1.     ,  1.     ])

In [78]:
np.polyval([1, -2, 0, 2], 4) # Evaluates a polynomial @ x = 4, taking coefficients as input

34

In [80]:
x = [1, 2, 3, 4, 5, 6, 7, 8]; y = [0, 2, 1, 3, 7, 10, 11, 19];# used to fit a polynomial of specified order to a set of data
                                                              # using a least-squares approach
np.polyfit(x, y, 3)

array([ 0.03282828, -0.06818182,  0.8037518 , -0.57142857])