# Eigenvalues
## Power Method

In [2]:
from __future__ import division, print_function
import numpy as np

def power(a, tol=1e-12, maxiter=30):
    n, m = a.shape
    if n != m:
        return None
    x = np.ones((n,), dtype=float)
    x = np.dot(a, x)
    L = max(abs(x))
    x = x / L
    k = 0
    while True:
        k += 1
        x = np.dot(a, x)
        Lnew = x[0]
        x = x / Lnew
        diff = abs(Lnew - L) / Lnew * 100
        if diff <= tol:
            break
        elif k > maxiter:
            break
        else:
            L = Lnew
    if diff <= tol:
        print(k)
        return L, x
    else:
        print(k)
        return None

a1 = np.array([[40, -20, 0], [-20, 40, -20], [0, -20, 40]], dtype=float)
print(a1)

L1, x1 = power(a1)
print(L1, x1)
L, x = np.linalg.eig(a1)
print(L)
print(x)

[[ 40. -20.   0.]
 [-20.  40. -20.]
 [  0. -20.  40.]]
21
68.2842712475 [ 1.         -1.41421356  1.        ]
[ 68.28427125  40.          11.71572875]
[[ -5.00000000e-01  -7.07106781e-01   5.00000000e-01]
 [  7.07106781e-01  -1.28369537e-16   7.07106781e-01]
 [ -5.00000000e-01   7.07106781e-01   5.00000000e-01]]


In [3]:
a2 = np.array([[4, -1, 1], [1, 1, 1], [-2, 0, -6]], dtype=float)
L2, x2 = power(a2)
print(L2)
print(x2)

L, x = np.linalg.eig(a2)
print(L)
print(x)

3
12.2
[  1.     2.9  -27.56]
[-5.76851284  3.46936062  1.29915222]
[[-0.11401985 -0.9338679   0.37892254]
 [-0.12869703 -0.29830718  0.91958565]
 [ 0.98510738  0.19723991 -0.10382645]]


## Inverse Power Method

In [4]:
def invpower(a, tol=1e-6, maxiter=60):
    L, x = power(np.linalg.inv(a), tol, maxiter)
    return 1.0 / L, x

a = np.array([[4, -1, 1], [1, 1, 1], [-2, 0, -6]], dtype=float)
L1, x1 = power(a1)
print(L1)
print(x1)

L, x = np.linalg.eig(a1)
print(L)
print(x)

21
68.2842712475
[ 1.         -1.41421356  1.        ]
[ 68.28427125  40.          11.71572875]
[[ -5.00000000e-01  -7.07106781e-01   5.00000000e-01]
 [  7.07106781e-01  -1.28369537e-16   7.07106781e-01]
 [ -5.00000000e-01   7.07106781e-01   5.00000000e-01]]


In [6]:
def eig(a, tol=1e-6, maxiter=60):
    n, m = a.shape
    if n != m:
        return None
    xx = np.ones((n,), dtype=float)
    for i in range(n):
        print(i, a[i,i])
        b = a - a[i,i] * np.eye(n, dtype=float)
        print(b)
        L, x = invpower(b, xx)
    return x

x = eig(a)
print(x)

0 4.0
[[  0.  -1.   1.]
 [  1.  -3.   1.]
 [ -2.   0. -10.]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()