# Iterative Methods
## Jacobi Method
Jacobi method is an iterative method.
$$x_{i}^{(k)} = \frac{b_i - \sum_{j=0}^{i-1} a_{ij} \, x_{j}^{(k-1)} - \sum_{j=i+1}^{n} a_{ij} \, x_{j}^{(k-1)}}{a_{ii}}$$

## Gauss-Seidel Method
Jacobi method is an iterative method.
$$x_{i}^{(k)} = \frac{b_i - \sum_{j=0}^{i-1} a_{ij} \, x_{j}^{(k)} - \sum_{j=i+1}^{n} a_{ij} \, x_{j}^{(k-1)}}{a_{ii}}$$

The main difference between Jacobi method and Gauss-Seidel method is that Jacobi method uses the previous values $x_{j}^{(k-1)}, \quad j=0,1, \ldots , i-1, i+1, i+2, \ldots , n$ to calculate the new values $x_{i}^{(k)}, \quad i=0,1, \ldots , n$. On the other hand, Gauss-Seidel method uses the new values $x_{j}^{(k)}$ when available and previous values otherwise. When determining $x_{i}^{(k)}$, available new values are $x_{j}^{(k)}, \quad  j=0,1, \ldots , i-1$ and previous values are $x_{j}^{(k-1)}, \quad  j=i+1, i+2, \ldots , n$.

In [1]:
from __future__ import division, print_function
import numpy as np

#a = np.array([ [4.0, -1, 1], [-1, 4, -2], [1, -2, 4]], dtype=float)
#b = np.array([12.0, -1.0, 5.0])
a = np.array([ [5, 4, 1], [10, 9, 4], [10, 13, 15]], dtype=float)
b = np.array([6.8, 17.6, 38.4])
#a = np.array([ [8, 2, 1], [1, 6, 2], [4, 0, 5]], dtype=float)
#b = np.array([-11.5, 18.5, 12.5])

print(a)
print(b)
print(np.linalg.solve(a, b))

[[  5.   4.   1.]
 [ 10.   9.   4.]
 [ 10.  13.  15.]]
[  6.8  17.6  38.4]
[ 0.4  0.8  1.6]


Let us try out the Jacoby method. Let us begin with one iteration of Jacobi method wherein we calculate $\{ x' \}$ from a given $[A], \{ b \}$ and $\{ x \}$. Clearly, we must have $[A], \{ b \}$ and $\{ x \}$ and we must compute $\{ x' \}$.

Since we can assume $\{ x \}$ to be anything, let us assume $\{ x \}$ to contain all ones (or zeros, if you want). Let us also arbitrarily fix the maximum number of iterations that we wish to carry out and the tolerance to check for convergence.

In [2]:
x = np.ones_like(b)
xx = np.zeros_like(b)
maxiter = 50
tol = 1e-12

for i in range(len(a)):
    s = np.dot(a[i, :i], x[:i]) + np.dot(a[i, i+1:], x[i+1:])
    xx[i] = (b[i] - s) / a[i, i]
diff = np.max(np.abs(xx - x))
print(diff, x, xx)

0.64 [ 1.  1.  1.] [ 0.36        0.4         1.02666667]


Now that we know how one iteration is carried out, let us repeat that iteration until either we exceed the maximum number of iterations allowed or the solution converges.

In [3]:
x = np.ones_like(b)
xx = np.zeros_like(b)
itr = 0
while itr <= maxiter:
    itr += 1
    for i in range(len(a)):
        s = np.dot(a[i, :i], x[:i]) + np.dot(a[i, i+1:], x[i+1:])
        xx[i] = (b[i] - s) / a[i, i]
    diff = np.max(np.abs(xx - x))
    print(itr, diff, x, xx)
    if diff > tol:
        x = xx.copy()
    else:
        break
print(itr, diff, xx)

1 0.64 [ 1.  1.  1.] [ 0.36        0.4         1.02666667]
2 0.946666666667 [ 0.36        0.4         1.02666667] [ 0.83466667  1.09925926  1.97333333]
3 0.948148148148 [ 0.83466667  1.09925926  1.97333333] [ 0.08592593  0.15111111  1.0508642 ]
4 1.32088888889 [ 0.08592593  0.15111111  1.0508642 ] [ 1.02893827  1.39303155  2.37175309]
5 1.70500594422 [ 1.02893827  1.39303155  2.37175309] [-0.22877586 -0.24182167  0.66674714]
6 2.25534887974 [-0.22877586 -0.24182167  0.66674714] [ 1.42010791  1.91341889  2.92209602]
7 2.96713099968 [ 1.42010791  1.91341889  2.92209602] [-0.75515432 -0.92105147 -0.04503498]
8 3.90671579197 [-0.75515432 -0.92105147 -0.04503498] [ 2.10584817  2.81463145  3.86168081]
9 5.14492685159 [ 2.10584817  2.81463145  3.86168081] [-1.66404132 -2.10057833 -1.28324604]
10 6.77310813671 [-1.66404132 -2.10057833 -1.28324604] [ 3.29711187  4.37482193  5.4898621 ]
11 8.91944902026 [ 3.29711187  4.37482193  5.4898621 ] [-3.23782997 -4.14784079 -3.42958692]
12 11.7429355805 

We can now convert the steps into a function and test it.

In [5]:
def jacobi(a, b, x, maxiter = 100, tol = 1e-12):
    itr = 0
    while itr <= maxiter:
        itr += 1
        for i in range(len(a)):
            s = np.dot(a[i, :i], x[:i]) + np.dot(a[i, i+1:], x[i+1:])
            xx[i] = (b[i] - s) / a[i, i]
        diff = np.max(np.abs(xx - x))
        print(itr, diff, x, xx)
        if diff > tol:
            x = xx.copy()
        else:
            break
    return itr, xx

a = np.array([ [4.0, -1, 1], [-1, 4, -2], [1, -2, 4]], dtype=float)
b = np.array([12.0, -1.0, 5.0])
#a = np.array([ [5, 4, 1], [10, 9, 4], [10, 13, 15]], dtype=float)
#b = np.array([6.8, 17.6, 38.4])
#a = np.array([ [8, 2, 1], [1, 6, 2], [4, 0, 5]], dtype=float)
#b = np.array([-11.5, 18.5, 12.5])
print('Jacobi Method')
print(a)
print(b)
print('Solution:', np.linalg.solve(a, b))
print()
x = np.ones_like(b)
itr, x = jacobi(a, b, x, tol=1e-6)
print(itr, x)

Jacobi Method
[[ 4. -1.  1.]
 [-1.  4. -2.]
 [ 1. -2.  4.]]
[ 12.  -1.   5.]
Solution: [ 3.  1.  1.]

1 2.0 [ 1.  1.  1.] [ 3.   0.5  1.5]
2 0.75 [ 3.   0.5  1.5] [ 2.75  1.25  0.75]
3 0.4375 [ 2.75  1.25  0.75] [ 3.125   0.8125  1.1875]
4 0.3125 [ 3.125   0.8125  1.1875] [ 2.90625  1.125    0.875  ]
5 0.2109375 [ 2.90625  1.125    0.875  ] [ 3.0625     0.9140625  1.0859375]
6 0.14453125 [ 3.0625     0.9140625  1.0859375] [ 2.95703125  1.05859375  0.94140625]
7 0.0986328125 [ 2.95703125  1.05859375  0.94140625] [ 3.02929688  0.95996094  1.04003906]
8 0.0673828125 [ 3.02929688  0.95996094  1.04003906] [ 2.97998047  1.02734375  0.97265625]
9 0.0460205078125 [ 2.97998047  1.02734375  0.97265625] [ 3.01367188  0.98132324  1.01867676]
10 0.0314331054688 [ 3.01367188  0.98132324  1.01867676] [ 2.99066162  1.01275635  0.98724365]
11 0.0214691162109 [ 2.99066162  1.01275635  0.98724365] [ 3.00637817  0.99128723  1.00871277]
12 0.0146636962891 [ 3.00637817  0.99128723  1.00871277] [ 2.99564362 

Gauss-Seidel method differs from Jacobi method in only one aspect, it uses some new values and remaining previous values of $\{ x \}$. We can copy Jacobi function verbatim and make the few necessary changes to obtain Gauss-Seidel method.

In [7]:
def gauss_seidel(a, b, x, maxiter = 100, tol = 1e-12):
    itr = 0
    while itr <= maxiter:
        itr += 1
        xx = x.copy()
        for i in range(len(a)):
            s = np.dot(a[i, :i], xx[:i]) + np.dot(a[i, i+1:], xx[i+1:])
            xx[i] = (b[i] - s) / a[i, i]
        diff = np.max(np.abs(xx - x))
        print(itr, diff, x, xx)
        if diff > tol:
            x = xx.copy()
        else:
            break
    return itr, xx

#a = np.array([ [4.0, -1, 1], [-1, 4, -2], [1, -2, 4]], dtype=float)
#b = np.array([12.0, -1.0, 5.0])
#a = np.array([ [5, 4, 1], [10, 9, 4], [10, 13, 15]], dtype=float)
#b = np.array([6.8, 17.6, 38.4])
a = np.array([ [8, 2, 1], [1, 6, 2], [4, 0, 5]], dtype=float)
b = np.array([-11.5, 18.5, 12.5])

print(a)
print(b)
print('Solution:', np.linalg.solve(a, b))
print()
x = np.ones_like(b)
print('Jacobi Method')
itr, x = jacobi(a, b, x, tol=1e-6)
print(itr, x)
print()

x = np.ones_like(b)
print('Gauss-Seidel Method')
itr, x = gauss_seidel(a, b, x, tol=1e-6)
print(itr, x)

[[ 8.  2.  1.]
 [ 1.  6.  2.]
 [ 4.  0.  5.]]
[-11.5  18.5  12.5]
Solution: [-2.5  2.   4.5]

Jacobi Method
1 2.8125 [ 1.  1.  1.] [-1.8125      2.58333333  1.7       ]
2 2.25 [-1.8125      2.58333333  1.7       ] [-2.29583333  2.81875     3.95      ]
3 0.669444444444 [-2.29583333  2.81875     3.95      ] [-2.6359375   2.14930556  4.33666667]
4 0.272083333333 [-2.6359375   2.14930556  4.33666667] [-2.51690972  2.07710069  4.60875   ]
5 0.110532407407 [-2.51690972  2.07710069  4.60875   ] [-2.53286892  1.96656829  4.51352778]
6 0.0395358796296 [-2.53286892  1.96656829  4.51352778] [-2.49333304  2.00096889  4.52629514]
7 0.0316287037037 [-2.49333304  2.00096889  4.52629514] [-2.50352912  1.99012379  4.49466644]
8 0.012242246576 [-2.50352912  1.99012379  4.49466644] [-2.49686425  2.00236604  4.50282329]
9 0.0053318904321 [-2.49686425  2.00236604  4.50282329] [-2.50094442  1.99853628  4.4974914 ]
10 0.00326413507909 [-2.50094442  1.99853628  4.4974914 ] [-2.49932049  2.0009936   4.50075554

## Improvements
With just a few minor changes, Gauss-Seidel method can be modified into the **successive over-relaxation method**.

## References
1. [Wikipedia article on Gauss-Seidel method](https://en.wikipedia.org/wiki/Gauss%E2%80%93Seidel_method)
2. [Wolfram MathWorld article on Gauss-Seidel method](http://mathworld.wolfram.com/Gauss-SeidelMethod.html)
3. [Wikipedia article on Jacobi method](https://en.wikipedia.org/wiki/Jacobi_method)
4. [Wolfram MathWorld article on Jacobi method](http://mathworld.wolfram.com/JacobiMethod.html)
5. [Wikipedia article on Successive Over-relaxation method](https://en.wikipedia.org/wiki/Successive_over-relaxation)
6. [Wolfram MathWorld article on Successive Over-relaxation method](http://mathworld.wolfram.com/SuccessiveOverrelaxationMethod.html)