# Largest Eigenvalue using Power Method

## Introduction
Linear algebraic equations are of the general form
$$ [A]\{x \} = \{b \} $$
If $\{ b \} \neq 0$, that is, at least one element of $\{ b \}$ is non-zero, equations are said to _nonhomogeneous_. If the equations are linearly independent, they will have a unique solution. In contrast, _homogeneous_ equations has a right hand side equal to zero:
$$ [A]\{x \} = \{ 0 \} $$
One obvious solution to this set of equations is $\{ x \} = \{ 0 \}$. This in most cases has little significance for physical systems and hence is called the _trivial solution_. The solution of interest must be _non-trivial_. Eigenvalue problems associated with engineering problems are usually of the form:
$$ \left[ [A] - \lambda [I] \right] \{ x \} = \{ 0 \} $$
where $\lambda$ is called the eigenvalue. Thus, instead of setting the $\{ x \} = \{ 0 \}$, we can satisfy the equation by determining $\lambda$ such that the equations are satisfied. One way to solve such a set of homogeneous equations is to equate the following determinant to zero
$$| [A] - \lambda [I] | = 0$$
Expanding the determinant yields a polynomial in $\lambda$, which is called the _characteristic polynomial_. The order of the polynmial is the same as the size of the coefficient matrix. The roots of this polynomial are the eigenvalues.

## Power Method
The power  method is an iterative approach that can be used to compute the largest or dominant eigenvalue and the corresponding eigenvector. With slight modification, it can also be used to determine the smallest eigenvalue and the corresponding eigenvector. To implement the power method, the system being analyzed must be expressed in the form
$$[A] \{ x \} = \lambda \{ x \}$$

## Problem Definition
To develop an algorithm to determine the largest eigenvalue and corresponding eigenvector of a given coefficient matrix starting from an assumed eigenvector given as input. Iterations will be carried out either until eigenvalue reaches a specified tolerance or until a specified maximum number of iterations are completed without reaching the specified tolerance.

## Theory
The eigenvalue problem is expressed in the following form for the purpose of the power method:
$$[A] \{ x \} = \lambda \{ x \}$$
where $[A]$ is the given coefficient matrix, which must be a square matrix, and $\{ x \}$ is the assumed eigenvector which can conveniently be assumed to be a vector with all elements equal to 1. We can then calculate the matrix product $\{ x' \} = [A] \{ x \}$ and normalize it with respect to one of the elements, usually the largest element ignoring the sign. This is the eigenvalue $\lambda$. If the normalized eigenvector $\{ x' \}$ is same as the initial vector $\{ x \}$ within the specified tolerance, the eigenvalue and eigenvector have been found. Otherwise, we must repeat these calculations until solution converges. One way to test for convergence is to compare the current value of $\lambda$ with the previous value and test if it is within the specified tolerance. If yes, eigenvalue has been found. Otherwise iteration must be continued, either until required tolerance is reached or until maximum number of iterations is exceeded.

## Variables
### Input Variables
$[A]$ the square matrix whose largest eigenvalue and corresponding eigenvector are to be found.

$\{ x \}$ the initial guess for the eigenvector, which can conveniently be taken as containing all ones.

``tol`` the specified tolerance for $\frac{|\lambda' - \lambda|}{\lambda}$

``maxiter`` the maximum number of iterations to be performed

### Output Variables
$\lambda$ the largest eigenvalue of the given coefficient matrix $[A]$. None in case solution does not converge within the specified number of iterations.

$\{ x \}$ the eigenvector corresponding to the largest eigenvector. None in case solution does not converge within the specified number of iterations.

## Algorithm
1. Input $[A]$ and assume $\{ x \}$
2. Compute $\{ x' \} = [A] \{ x \}$.
3. Determine the largest value amongst the elements of $[A]$ and store as $\lambda'$.
4. Normalize $\{ x' \}$ by dividing all its elements by $\lambda$.
5. $i = 0$
6. Start iterations
   1. $i = i + 1$
   2. $\{ x \} = \{ x' \}$
   3. $\lambda = \lambda'$
   4. $\{ x' \} = [A] \{ x \}$
   5. $\lambda' = max(\{ x' \})$
   6. $\{ x' \} = \frac{ \{ x' \} }{\lambda'}$
   7. $error = \left| \frac{\lambda' - \lambda}{\lambda} \right| $
   8. If $error \leq tol$ return $\lambda$ and $\{ x' \}$. Else if $i = maxiter$ stop iterations and return None and None. Else if $i < maxiter$, continue iterations

In [2]:
from __future__ import division
import numpy as np

def power(a, x, eps=1e-6, niter=50, verbose=False):
    
    xnew = np.dot(a, x)
    wnew = xnew[np.abs(xnew).argmax()]
    xnew = xnew / wnew
    i = 0

    while i <= niter:
        i += 1
        w = wnew
        x = xnew[:]
        xnew = np.dot(a, x)
        wnew = xnew[np.abs(xnew).argmax()]
        xnew = xnew / wnew
        diff = np.abs(wnew - w)
        if verbose:
            print "%5d %12.4f %12.4f %12.6f" %  (i, w, wnew, diff),
            print xnew
        if diff <- eps:
            break

    if abs(diff) > eps:
        print 'Solution did not converge'
        return None, None
    else:
        return w, x

# Solved example 13.3 from Chapra, S.C., Applied Numerical Methods with MATLAB for Engineers and Scientists, 3ed., 
# McGraw Hill, 2008
a = np.array([[40, -20, 0], 
              [-20, 40, -20], 
              [0, -20, 40]], dtype=float)
x = np.ones((3,), dtype=float)
print a
ww, xx = np.linalg.eig(a)
print 'Answer using np.eig()'
print ww[0]
print xx[:,0]

w, x = power(a, x, 1e-6, 100)
print
print 'Answer using power() function'
print 'Largest eigenvalue =', w
print 'Eigenvector =', x

[[ 40. -20.   0.]
 [-20.  40. -20.]
 [  0. -20.  40.]]
Answer using np.eig()
68.2842712475
[-0.5         0.70710678 -0.5       ]

Answer using power() function
Largest eigenvalue = 68.2842712475
Eigenvector = [-0.70710678  1.         -0.70710678]


## Results and Discussion
Note that the eigenvalue obtained using **``power()``** function is identical to that obtained using **``np.linalg.eig()``** but the eigenvector is not. But it is proportional to it. If we normalize the eigenvector obtained from **``np.linalg.eig()``**, it will be found to be the same.

In [3]:
xxx =xx[:,0]
print np.abs(xxx).argmax()
print xx[:,0] / xxx[np.abs(xxx).argmax()]

1
[-0.70710678  1.         -0.70710678]


## Improvements
### Smallest Eigenvalue
Inverse power method can determine the smallest eigenvalue of the given coefficient matrix $[A]$ and the corresponding eigenvector. It involves inverting the given coefficient matrix $[A]$ and determining its largest eigenvalue and corresponding eigenvector using power method. The inverse of this calculated largest eigenvector is the smallest eigenvalue of the given coefficient matrix.

In [4]:
aa = np.linalg.inv(a)
x = np.ones((aa.shape[0],))
w2, x2 = power(aa, x)
print ww[-1], 1.0 / w2
print xx[:,-1] / np.max(np.abs(xx)), x2

11.7157287525 11.7157287525
[ 0.70710678  1.          0.70710678] [ 0.70710678  1.          0.70710678]


### Intermediate Eigenvalues
It is possible to determine the remaining intermediate eigenvalues and the corresponding eigenvectors by _deflation_. This is left as an exercise to the motivated student.

It is also possible to plot a graph of the eigenvector, which in many problems has a pysical interpretation.

## References
1. Chapra, S.C. and Canale, R.P., _Numerical Methods for Engineers_, 6ed., McGraw Hill, 2010 (Chapter 27. Boundary Value and Eigenvalue Problems, pp. 778).
2. Chapra, S.C., _Applied Numerical Methods with MATLAB for Engineers and Scientists, 3ed., McGraw Hill, 2008 (Chapter 13. Eigenvalues, pp. 303).

## Applications
### Principal Stress and Principal Direction
In a solid subjected to three-dimensional state of stress, the state of stress is expressed in the form of the stress matrix:
$$
\begin{align*}
[\sigma] & = \begin{bmatrix}
\sigma_x  & \tau_{xy} & \tau_{xz} \\
\tau_{xy} & \sigma_y  & \tau_{yz} \\
\tau_{xz} & \tau_{yz} & \sigma_z
\end{bmatrix}
\end{align*}
$$
where $\sigma_x, \sigma_y, \sigma_z$ are normal stresses and $\tau_{xy}, \tau_{yz}, \tau_{xz}$ are shear stresses. Principal stresses and are given by the eigenvalues of the stress matrix $[\sigma]$ and the principal planes by the eigenvectors.

In [12]:
s = np.diag([100.0, -120.0, 25.0])

s[0,1] = s[1,0] = 75
s[0,2] = s[2,0] = 50
s[1,2] = s[2,1] = 20
print s

ww, xx = np.linalg.eig(s)
print ww

x = np.array([1, 1, 1], dtype=float)
w, x = power(s, x, 1e-6, 1000)
print w

[[ 100.   75.   50.]
 [  75. -120.   20.]
 [  50.   20.   25.]]
[ 146.80049737 -143.25673922    1.45624185]
146.800497369


### Free Vibration of Multi Degree of Freedom Systems
Free vibration of an MDOF system consists of determining the fundamental natural period of vibration of the system and its mode shape. These attributes are characteristic of the vibrating system and are useful in determining the dynamic response of systems under free and forced vibration.

The dynamic matrix $[D]$ of a system is obtained as:
$$[D] = [K]^{-1} [M]$$
where $[K]$ is the stiffness matrix and $[M]$ is the mass matrix of the system. For a simple spring mass system with three masses, with each mass connected in sequence, mass matrix $[M]$ is obtained as:
$$\begin{align*}
[M] & = \begin{bmatrix}
m_1 & 0 & 0 \\ 0 & m_2 & 0 \\ 0 & 0 & m_3
\end{bmatrix} \\
[K] & = \begin{bmatrix}
k_1 + k_2  & -k_2  & 0 \\
-k_1 & k_2 + k_3 & -k_2 \\
0 & -k_2 & k_3
\end{bmatrix}
\end{align*}
$$
Fundamental natural frequency is obtained as the inverse of the largest eigenvalue of the dynamic matrix $[D]$.

In [13]:
def mass_matrix(m):
    return np.diag(m)

m = np.array([12, 10, 8], dtype=float) * 1e3
print m
M = mass_matrix(m)
print M

[ 12000.  10000.   8000.]
[[ 12000.      0.      0.]
 [     0.  10000.      0.]
 [     0.      0.   8000.]]


In [14]:
def stiffness_matrix(k):
    K = np.diag(k) - np.diag(k[:-1], 1) - np.diag(k[:-1], -1)
    for i in range(len(k)-1):
        K[i,i] += k[i+1]
    return K

k = np.array([30, 24, 18], dtype=float) * 100
print len(k), range(len(k-1))
print k
K = stiffness_matrix(k)
print K

3 [0, 1, 2]
[ 3000.  2400.  1800.]
[[ 5400. -3000.     0.]
 [-3000.  4200. -2400.]
 [    0. -2400.  1800.]]


In [15]:
def dynamic_matrix(m, k):
    M = mass_matrix(m)
    K = stiffness_matrix(k)
    return np.dot(np.linalg.inv(K), M)

D = dynamic_matrix(m, k)
print D
print
ww, xx = np.linalg.eig(D)
print 'np.linalg.eig()'
print ww
print xx
print
x = np.array([1, 1, 1], dtype=float)
w, x = power(D, x)
print w
print x

[[ -3.33333333  -8.33333333  -8.88888889]
 [-10.         -15.         -16.        ]
 [-13.33333333 -20.         -16.88888889]]

np.linalg.eig()
[-39.43152714   2.9246909    1.28461401]
[[ 0.31932763  0.64314997  0.55614305]
 [ 0.60718286  0.27805567 -0.73064727]
 [ 0.72757051 -0.7134726   0.39605489]]

-39.4315271409
[ 0.43889578  0.83453473  1.        ]


In [16]:
help(power)

Help on function power in module __main__:

power(a, x, eps=1e-06, niter=50, verbose=False)
    power(a, x, eps, niter) -> w, x
    
    a   - 2 dimensioned array whose largest eigenvalue and corresponding eigenvector are to be determined
    x   - initial guess for the eigenvector
    eps - tolerance to determine when to stop iterations
    niter - maximum number of iterations if solution does not converge to required tolerance
    
    w - largest eigenvalue
    x - corresponding eigenvector



In [20]:
def invpower(a, x, tol=1e-6, maxiter=60):
    L, x = power(np.linalg.inv(a), tol, maxiter)
    return 1.0 / L, x

a = np.array([[4, -1, 1], [1, 1, 1], [-2, 0, -6]], dtype=float)
x = np.ones(len(a), dtype=float)

L1, x1 = power(a, x)
print(L1)
print(x1)

L, x = np.linalg.eig(a)
print(L)
print(x)

aa = np.linalg.inv(a)
print a
print aa
print np.dot(a, aa)
a2, x2 = power(aa, x)

-5.76851284051
[-0.11574358 -0.13064265  1.        ]
[-5.76851284  3.46936062  1.29915222]
[[-0.11401985 -0.9338679   0.37892254]
 [-0.12869703 -0.29830718  0.91958565]
 [ 0.98510738  0.19723991 -0.10382645]]
[[ 4. -1.  1.]
 [ 1.  1.  1.]
 [-2.  0. -6.]]
[[ 0.23076923  0.23076923  0.07692308]
 [-0.15384615  0.84615385  0.11538462]
 [-0.07692308 -0.07692308 -0.19230769]]
[[  1.00000000e+00   5.55111512e-17   0.00000000e+00]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00]
 [  5.55111512e-17   0.00000000e+00   1.00000000e+00]]


IndexError: index 5 is out of bounds for axis 0 with size 3

In [14]:
print(x[:,0] / x[2,0])

[-0.11574358 -0.13064265  1.        ]
